AppCenar/Controllers/CategoryController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AppCenar.Models;

namespace AppCenar.Controllers
{
    public class CategoryController : Controller
    {
        private UsersContext db = new UsersContext();

        //
        // GET: /Category/

        public ActionResult Index()
        {
            return View(db.Category.ToList());
        }

        //
        // GET: /Category/Details/5

        public ActionResult Details(int id = 0)
        {
            Category category = db.Category.Find(id);
            if (category == null)
            {
                return HttpNotFound();
            }
            return View(category);
        }

        //
        // GET: /Category/Create

        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /Category/Create

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Category category)
        {
            if (ModelState.IsValid)
            {
                db.Category.Add(category);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(category);
        }

        //
        // GET: /Category/Edit/5

        public ActionResult Edit(int id = 0)
        {
            Category category = db.Category.Find(id);
            if (category == null)
            {
                return HttpNotFound();
            }
            return View(category);
        }

        //
        // POST: /Category/Edit/5

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Category category)
        {
            if (ModelState.IsValid)
            {
                db.Entry(category).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(category);
        }

        //
        // GET: /Category/Delete/5

        public ActionResult Delete(int id = 0)
        {
            Category category = db.Category.Find(id);
            if (category == null)
            {
                return HttpNotFound();
            }
            return View(category);
        }

        //
        // POST: /Category/Delete/5

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Category category = db.Category.Find(id);
            db.Category.Remove(category);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

AppCenar/Controllers/CheckoutController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AppCenar.Controllers
{
    public class CheckoutController : Controller
    {
        //
        // GET: /Checkout/

        public ActionResult Index()
        {
            return View();
        }

    }
}

AppCenar/Controllers/ContactsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AppCenar.Controllers
{
    public class ContactsController : Controller
    {
        //
        // GET: /Contacts/

        public ActionResult Index()
        {
            return View();
        }

    }
}

AppCenar/Controllers/OrderController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AppCenar.Controllers
{
    public class OrderController : Controller
    {
        //
        // GET: /Order/

        public ActionResult Index()
        {
            return View();
        }

    }
}

AppCenar/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <title>@ViewBag.Title - My ASP.NET MVC Application</title>
    <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
    <meta name="viewport" content="width=device-width" />
    @Styles.Render("~/Content/themes/appCenar")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/appCenarJs")
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
    <!--webfont-->
    <link href="~/Content/css/FontSourceSans.css" rel="stylesheet" />
    <link href="~/Content/css/FontLobster.css" rel="stylesheet" />
    <!--Animation-->
    <script src="~/Scripts/wow.min.js"></script>
    <script>
        new WOW().init();
    </script>
    <script type="text/javascript">
        jQuery(document).ready(function ($) {
            $(".scroll").click(function (event) {
                event.preventDefault();
                $('html,body').animate({ scrollTop: $(this.hash).offset().top }, 1200);
            });
        });
    </script>
</head>
<body>
    <!-- header-section-starts -->
    <div class="header">
        <!-- header-section-starts -->
        <div class="header">
            <div class="container">
                <div class="top-header">
                    <div class="logo">
                        <a href="@Url.Action("Index", "Home")">
                            <img src="~/Images/appcenar.png" style="height: auto; width: 220px;" class="img-responsive" alt="" /></a>
                    </div>
                    <div class="queries">
                        <p>
                            Preguntas? siéntete libre de llamarnos!<span>+1 (829)-427-1746 </span>
                            <label>(11AM to 11PM)</label>
                        </p>
                    </div>
                    <div class="header-right">
                        <div class="cart box_1">
                            <a href="@Url.Action("Index", "Checkout")">
                                <h3><span class="simpleCart_total">$0.00 </span>(<span id="simpleCart_quantity" class="simpleCart_quantity"> 0 </span>Articulos)<img src="~/Images/bag.png" alt=""></h3>
                            </a>
                            <p><a href="javascript:;" class="simpleCart_empty">Limpiar carro</a></p>
                            <div class="clearfix"></div>
                        </div>
                    </div>
                    <div class="clearfix"></div>
                </div>
            </div>
        </div>
        <!-- header-section-ends -->
        <div class="menu-bar">
            <div class="container">
                <div class="top-menu">
                    <ul>
                        <li class="active"><a href="@Url.Action("Index", "Home")">Inicio</a></li>
                        |
                        <li><a href="@Url.Action("Index", "PopularRestaurant")">Restaurantes populares</a></li>
                        |
                        <li><a href="@Url.Action("Index", "Order")">Ordenar</a></li>
                        |
                        <li><a href="@Url.Action("Index", "Contacts")">Contactos</a></li>
                        <div class="clearfix"></div>
                    </ul>
                </div>

                @if (Request.IsAuthenticated)
                {
                    
                    <div class="login-section">
                        <a href="@Url.Action("Create", "PopularRestaurant")">Crear Restaurant</a> | <a href="@Url.Action("Create", "Category")">Crear Categoria</a>
                        <br/> <br />
                        <span style="color: black">Binvenido, @User.Identity.Name!</span>

                        @using (Html.BeginForm("LogOff", "Account", FormMethod.Post, new { id = "logoutForm" }))
                        {
                            @Html.AntiForgeryToken()
                            <a style="    color: red;float: left;margin-left: 140px;margin-top: -18px;" href="javascript:document.getElementById('logoutForm').submit()">Log off</a>
                        }
                    </div>
                }
                else
                {
         
                    <div class="login-section">
                        <ul>
                            <li><a href="@Url.Action("Login", "Account")">Iniciar Session</a> </li>
                            |
                    <li><a href="@Url.Action("Register", "Account")">Register</a> </li>

                            <div class="clearfix"></div>
                        </ul>
                    </div>
                    <div class="clearfix"></div>
                }




            </div>
        </div>

    </div>
    <!-- header-section-ends -->
    <div id="body">
        @RenderSection("featured", required: false)
        <section class="content-wrapper main-content clear-fix">
            @RenderBody()
        </section>
    </div>
    <!-- footer-section-starts -->
    <div class="footer">
        <div class="container">
            @*      <p class="wow fadeInLeft" data-wow-delay="0.4s">&copy; 2014  All rights  Reserved | Template by &nbsp;<a href="http://w3layouts.com" target="target_blank">W3Layouts</a></p>
      *@
        </div>
    </div>

    <!-- footer-section-ends -->
    <script type="text/javascript">
        $(document).ready(function () {

            var defaults = {
                containerID: 'toTop', // fading element id
                containerHoverID: 'toTopHover', // fading element hover id
                scrollSpeed: 1200,
                easingType: 'linear'
            };


            $().UItoTop({ easingType: 'easeOutQuart' });

        });
    </script>
    <a href="#" id="toTop" style="display: block;"><span id="toTopHover" style="opacity: 1;"></span></a>

    @RenderSection("scripts", required: false)
</body>
</html>