AppCenar/Controllers/OrderListController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AppCenar.Models;

namespace AppCenar.Controllers
{
    public class OrderListController : Controller
    {

        private UsersContext db = new UsersContext();

        //
        // GET: /OrderList/
        public ActionResult Index(int idRestaurant)
        {
            var detalles = db.RestaurantDetails.Where(x => x.IdRestaurant == idRestaurant).ToList();

            return View(detalles);
        }

    }
}

AppCenar/Controllers/PopularRestaurantController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AppCenar.Models;

namespace AppCenar.Controllers
{
    public class PopularRestaurantController : Controller
    {
        private UsersContext db = new UsersContext();

        //
        // GET: /PopularRestaurant/

        public ActionResult Index()
        {
            return View(db.Restaurant.ToList());
        }

        //
        // GET: /PopularRestaurant/Details/5

        public ActionResult Details(int id = 0)
        {
            Restaurant restaurant = db.Restaurant.Find(id);
            if (restaurant == null)
            {
                return HttpNotFound();
            }
            return View(restaurant);
        }

        //
        // GET: /PopularRestaurant/Create

        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /PopularRestaurant/Create

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Restaurant restaurant)
        {
            if (ModelState.IsValid)
            {
                db.Restaurant.Add(restaurant);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(restaurant);
        }

        public ActionResult TrazarRuta(string location)
        {
            ViewBag.LocationRestaurant = location;

            return View();
        }

        //
        // GET: /PopularRestaurant/Edit/5
        public ActionResult Edit(int id = 0)
        {
            Restaurant restaurant = db.Restaurant.Find(id);
            if (restaurant == null)
            {
                return HttpNotFound();
            }
            return View(restaurant);
        }

        //
        // POST: /PopularRestaurant/Edit/5

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Restaurant restaurant)
        {
            if (ModelState.IsValid)
            {
                db.Entry(restaurant).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(restaurant);
        }

        //
        // GET: /PopularRestaurant/Delete/5

        public ActionResult Delete(int id = 0)
        {
            Restaurant restaurant = db.Restaurant.Find(id);
            if (restaurant == null)
            {
                return HttpNotFound();
            }
            return View(restaurant);
        }

        //
        // POST: /PopularRestaurant/Delete/5

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Restaurant restaurant = db.Restaurant.Find(id);
            db.Restaurant.Remove(restaurant);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

AppCenar/Controllers/RestaurantDetailsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AppCenar.Models;

namespace AppCenar.Controllers
{
    public class RestaurantDetailsController : Controller
    {
        private UsersContext db = new UsersContext();

        //
        // GET: /RestaurantDetails/

        public ActionResult Index()
        {
            return View(db.RestaurantDetails.ToList());
        }

        //
        // GET: /RestaurantDetails/Details/5

        public ActionResult Details(int id = 0)
        {
            RestaurantDetails restaurantdetails = db.RestaurantDetails.Find(id);
            if (restaurantdetails == null)
            {
                return HttpNotFound();
            }
            return View(restaurantdetails);
        }

        //
        // GET: /RestaurantDetails/Create

        public ActionResult Create(int idRestaurant)
        {
            var restaurant = new RestaurantDetails
            {
                IdRestaurant = idRestaurant
            };

            ViewBag.Categorys = new SelectList(db.Category.ToList(), "IdCategory", "Name");

            return View(restaurant);
        }

        //
        // POST: /RestaurantDetails/Create

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(RestaurantDetails restaurantdetails)
        {
            if (ModelState.IsValid)
            {
                db.RestaurantDetails.Add(restaurantdetails);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(restaurantdetails);
        }

        //
        // GET: /RestaurantDetails/Edit/5

        public ActionResult Edit(int id = 0)
        {
            RestaurantDetails restaurantdetails = db.RestaurantDetails.Find(id);
            if (restaurantdetails == null)
            {
                return HttpNotFound();
            }
            return View(restaurantdetails);
        }

        //
        // POST: /RestaurantDetails/Edit/5

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(RestaurantDetails restaurantdetails)
        {
            if (ModelState.IsValid)
            {
                db.Entry(restaurantdetails).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(restaurantdetails);
        }

        //
        // GET: /RestaurantDetails/Delete/5

        public ActionResult Delete(int id = 0)
        {
            RestaurantDetails restaurantdetails = db.RestaurantDetails.Find(id);
            if (restaurantdetails == null)
            {
                return HttpNotFound();
            }
            return View(restaurantdetails);
        }

        //
        // POST: /RestaurantDetails/Delete/5

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            RestaurantDetails restaurantdetails = db.RestaurantDetails.Find(id);
            db.RestaurantDetails.Remove(restaurantdetails);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

AppCenar/Views/PopularRestaurant/Create.cshtml
@model AppCenar.Models.Restaurant

@{
    ViewBag.Title = "Create";
}

<h2>Crear nuevo restaurante</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

        <div class="col-xs-12">
            <div class="form-group form-group-sm">
                @Html.LabelFor(c => c.Name)
                @Html.TextBoxFor(x => Model.Name, new { @class = "form-control" })
                @Html.ValidationMessageFor(f => f.Name, null, new { @class = "text-danger" })
            </div>
            <div class="form-group form-group-sm">
                @Html.LabelFor(model => model.Presupuesto)
                @Html.TextBoxFor(x => Model.Presupuesto, new { @class = "form-control" })
                @Html.ValidationMessageFor(f => f.Presupuesto, null, new { @class = "text-danger" })
            </div>
            <div class="form-group form-group-sm">
                @Html.LabelFor(model => model.Picture)
                @Html.TextBoxFor(x => Model.Picture, new { @class = "form-control" })
                @Html.ValidationMessageFor(f => f.Picture, null, new { @class = "text-danger" })
            </div>
            <div class="form-group form-group-sm">
                @Html.LabelFor(model => model.Rating)
                @Html.TextBoxFor(x => Model.Rating, new { @class = "form-control" })
                @Html.ValidationMessageFor(f => f.Rating, null, new { @class = "text-danger" })
            </div>
            <input type="submit" value="Crear" class="btn btn-primary pull-right" />
        </div>
        <div>
          <h4>@Html.ActionLink("Volver Atras", "Index", new { @class = "volverAtras" })</h4>  
        </div>
}

<br/>
<br/>
<br/>
<br/>
<br/>
<br/>


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

AppCenar/Views/PopularRestaurant/Delete.cshtml
@model AppCenar.Models.Restaurant

@{
    ViewBag.Title = "Eliminar";
}
<div class="text-center">
    <br />
    <h2>Eliminar Restaurante - @Model.Name</h2>
    <h3>Esta seguro de eliminar este restaurante?</h3>

    <br />
    <br />
    <div class="display-label">
        <h4>@Html.DisplayNameFor(model => model.Name)</h4>
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Name)
    </div>

    <br />
    <div class="display-label">
        <h4>@Html.DisplayNameFor(model => model.Presupuesto)</h4>
    </div>
    <br />
    <div class="display-field">
        @Html.DisplayFor(model => model.Presupuesto)
    </div>

    <br />
    <div class="display-label">
        <h4>@Html.DisplayNameFor(model => model.Picture)</h4>
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Picture)
    </div>
    <br />

    <div class="display-label">
        <h4>@Html.DisplayNameFor(model => model.Rating)</h4>
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Rating)
    </div>

    <br />
    <br />
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        <p>
            <input type="submit" class="btn btn-danger" value="Eliminar" />
            |
          <h4>@Html.ActionLink("Volver Atras", "Index", new { @class = "volverAtras" })</h4>  
        </p>
    }
</div>

<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />

AppCenar/Views/PopularRestaurant/Details.cshtml
@model AppCenar.Models.Restaurant

@{
    ViewBag.Title = "Editar";
}

<fieldset>
    <legend>Edicion Restaurante - @Model.Name</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Name)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Name)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Presupuesto)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Presupuesto)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Picture)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Picture)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Rating)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Rating)
    </div>
</fieldset>
<p>
    @Html.ActionLink("Edit", "Edit", new { id=Model.IdRestaurant }) |
    @Html.ActionLink("Back to List", "Index")
</p>

AppCenar/Views/PopularRestaurant/Edit.cshtml
@model AppCenar.Models.Restaurant

@{
    ViewBag.Title = "Editar";
}

<h2 class="text-center">Editar Restaurante - @Model.Name</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)
    @Html.HiddenFor(model => model.IdRestaurant)
        <div class="col-xs-12">
            <div class="form-group form-group-sm">
                @Html.LabelFor(c => c.Name)
                @Html.TextBoxFor(x => Model.Name, new { @class = "form-control" })
                @Html.ValidationMessageFor(f => f.Name, null, new { @class = "text-danger" })
            </div>
            <div class="form-group form-group-sm">
                @Html.LabelFor(model => model.Presupuesto)
                @Html.TextBoxFor(x => Model.Presupuesto, new { @class = "form-control" })
                @Html.ValidationMessageFor(f => f.Presupuesto, null, new { @class = "text-danger" })
            </div>
            <div class="form-group form-group-sm">
                @Html.LabelFor(model => model.Location)
                @Html.TextBoxFor(x => Model.Location, new { @class = "form-control" })
                @Html.ValidationMessageFor(f => f.Location, null, new { @class = "text-danger" })
            </div>
            <div class="form-group form-group-sm">
                @Html.LabelFor(model => model.Picture)
                @Html.TextBoxFor(x => Model.Picture, new { @class = "form-control" })
                @Html.ValidationMessageFor(f => f.Picture, null, new { @class = "text-danger" })
            </div>
            <div class="form-group form-group-sm">
                @Html.LabelFor(model => model.Rating)
                @Html.TextBoxFor(x => Model.Rating, new { @class = "form-control" })
                @Html.ValidationMessageFor(f => f.Rating, null, new { @class = "text-danger" })
            </div>
            <input type="submit" value="Guardar cambios" class="btn btn-primary pull-right" />
        </div>
        <div>
          <h4>@Html.ActionLink("Volver Atras", "Index", new { @class = "volverAtras" })</h4>  
        </div>
}
<br />
<br />
<br />
<br />
<br />
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

AppCenar/Views/PopularRestaurant/Index.cshtml
@model List<AppCenar.Models.Restaurant>

@{
    Layout = "~/Views/Shared/_Layout.cshtml";

    ViewBag.Title = "Restaurantes Populares";
}

<script src="~/Scripts/Restaurant/geo.js"></script>
<script src="~/Scripts/Restaurant/TraceRoute.js"></script>

<div class="Popular-Restaurants-content">
    <div class="Popular-Restaurants-grids">
        <div class="container">
            @foreach (var restaurant in Model)
            {
                <div class="Popular-Restaurants-grid wow fadeInRight" data-wow-delay="0.4s">
                    <div class="col-md-3 restaurent-logo">
                        <img src="@restaurant.Picture" class="img-responsive" alt="" />
                    </div>
                    <div class="col-md-2 restaurent-title">
                        <div class="logo-title">
                            <h4><a href="#">@restaurant.Name</a></h4>
                        </div>
                        <a class="logo-title" href="@Url.Action("TrazarRuta", "PopularRestaurant")?location=@restaurant.Location">Trazar Ruta</a>
                        <div class="rating">
                            <span>Ratings</span>
                              @if (@restaurant.Rating <= 3.9)
                            {
                                <a href="#">
                                    <img src="~/Images/star1.png" class="img-responsive" alt=""></a>                                    
                            }
                              @if (@restaurant.Rating >= 4)
                            {
                                <a href="#">
                                    <img src="~/Images/star2.png" class="img-responsive" alt=""></a>                                    
                            }
                        </div>
                    </div>
                    <div class="col-md-7 buy">
                        @if (Request.IsAuthenticated)
                        { 
                            <a href="@Url.Action("Create", "RestaurantDetails")?idRestaurant=@restaurant.IdRestaurant"> Crear Detalle</a>
                             <p>| @Html.ActionLink("Eliminar", "Delete", new { id= @restaurant.IdRestaurant })  |   @Html.ActionLink("Editar", "Edit", new { id= @restaurant.IdRestaurant })</p>
                              
                        }
                        <span>@restaurant.Presupuesto</span>
                        <a class="morebtn hvr-rectangle-in" href="@Url.Action("Index", "OrderList")?idRestaurant=@restaurant.IdRestaurant">Ver Menu</a>
                    </div>
                    <div class="clearfix"></div>
                </div>
            }
        </div>
    </div>
</div>

AppCenar/Views/PopularRestaurant/TrazarRuta.cshtml
<script type="text/javascript" src="http://maps.googleapis.com/maps/api/js?libraries=places&key=AIzaSyAfmb40DA2jKn1MfKJPrszigqMoBwQQt7s"></script>
<script type="text/javascript">
    var directionsDisplay, location2, location1;

    if (navigator.geolocation) {
        navigator.geolocation.getCurrentPosition(function (position) {
            location1 = position.coords.latitude + "," + position.coords.longitude;
        }, function () {
            alert("este navegador no soporta el uso de mapas.");
        });
    }
    var directionsService = new google.maps.DirectionsService();

    location2 = window.location.href.split("=")[1];

    function InitializeMap() {
        directionsDisplay = new google.maps.DirectionsRenderer();
        var latlng = new google.maps.LatLng(-34.397, 150.644);
        var myOptions =
        {
            zoom: 8,
            center: latlng,
            mapTypeId: google.maps.MapTypeId.ROADMAP
        };
        var map = new google.maps.Map(document.getElementById("map"), myOptions);
        directionsDisplay.setMap(map);
        directionsDisplay.setPanel(document.getElementById('directionpanel'));
        var control = document.getElementById('control');
        control.style.display = 'block';
        calcRoute();
    }

    function calcRoute() {
        var request = {
            origin: location1,
            destination: location2,
            travelMode: google.maps.DirectionsTravelMode.DRIVING
        };
        directionsService.route(request, function (response, status) {
            if (status == google.maps.DirectionsStatus.OK) {
                directionsDisplay.setDirections(response);
            }
        });
    }
    window.onload = InitializeMap;
</script>
<h1 class="text-center"> Ruta </h1>
<br/>
<br/>
<table id="control">
    <tr>
        <td valign="top">
            <div class="row">
                <div class="col-xs-6">
                    <div id="directionpanel" style="height: 390px; margin-left: 50px; overflow: auto"></div>

                </div>
                <div class="col-xs-6">
                    <div id="map" style="height: 450px; margin-left: 50px; width: 620px"></div>
                </div>
            </div>
        </td>
    </tr>
</table>
<br />
<br />